require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncomeValuesController do

  # This should return the minimal set of attributes required to create a valid
  # IncomeValue. As you add validations to IncomeValue, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncomeValuesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all income_values as @income_values" do
      income_value = IncomeValue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:income_values).should eq([income_value])
    end
  end

  describe "GET show" do
    it "assigns the requested income_value as @income_value" do
      income_value = IncomeValue.create! valid_attributes
      get :show, {:id => income_value.to_param}, valid_session
      assigns(:income_value).should eq(income_value)
    end
  end

  describe "GET new" do
    it "assigns a new income_value as @income_value" do
      get :new, {}, valid_session
      assigns(:income_value).should be_a_new(IncomeValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested income_value as @income_value" do
      income_value = IncomeValue.create! valid_attributes
      get :edit, {:id => income_value.to_param}, valid_session
      assigns(:income_value).should eq(income_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IncomeValue" do
        expect {
          post :create, {:income_value => valid_attributes}, valid_session
        }.to change(IncomeValue, :count).by(1)
      end

      it "assigns a newly created income_value as @income_value" do
        post :create, {:income_value => valid_attributes}, valid_session
        assigns(:income_value).should be_a(IncomeValue)
        assigns(:income_value).should be_persisted
      end

      it "redirects to the created income_value" do
        post :create, {:income_value => valid_attributes}, valid_session
        response.should redirect_to(IncomeValue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved income_value as @income_value" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeValue.any_instance.stub(:save).and_return(false)
        post :create, {:income_value => {}}, valid_session
        assigns(:income_value).should be_a_new(IncomeValue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeValue.any_instance.stub(:save).and_return(false)
        post :create, {:income_value => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested income_value" do
        income_value = IncomeValue.create! valid_attributes
        # Assuming there are no other income_values in the database, this
        # specifies that the IncomeValue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IncomeValue.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => income_value.to_param, :income_value => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested income_value as @income_value" do
        income_value = IncomeValue.create! valid_attributes
        put :update, {:id => income_value.to_param, :income_value => valid_attributes}, valid_session
        assigns(:income_value).should eq(income_value)
      end

      it "redirects to the income_value" do
        income_value = IncomeValue.create! valid_attributes
        put :update, {:id => income_value.to_param, :income_value => valid_attributes}, valid_session
        response.should redirect_to(income_value)
      end
    end

    describe "with invalid params" do
      it "assigns the income_value as @income_value" do
        income_value = IncomeValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => income_value.to_param, :income_value => {}}, valid_session
        assigns(:income_value).should eq(income_value)
      end

      it "re-renders the 'edit' template" do
        income_value = IncomeValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => income_value.to_param, :income_value => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested income_value" do
      income_value = IncomeValue.create! valid_attributes
      expect {
        delete :destroy, {:id => income_value.to_param}, valid_session
      }.to change(IncomeValue, :count).by(-1)
    end

    it "redirects to the income_values list" do
      income_value = IncomeValue.create! valid_attributes
      delete :destroy, {:id => income_value.to_param}, valid_session
      response.should redirect_to(income_values_url)
    end
  end

end
