require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VariableExpensesController do

  # This should return the minimal set of attributes required to create a valid
  # VariableExpense. As you add validations to VariableExpense, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VariableExpensesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all variable_expenses as @variable_expenses" do
      variable_expense = VariableExpense.create! valid_attributes
      get :index, {}, valid_session
      assigns(:variable_expenses).should eq([variable_expense])
    end
  end

  describe "GET show" do
    it "assigns the requested variable_expense as @variable_expense" do
      variable_expense = VariableExpense.create! valid_attributes
      get :show, {:id => variable_expense.to_param}, valid_session
      assigns(:variable_expense).should eq(variable_expense)
    end
  end

  describe "GET new" do
    it "assigns a new variable_expense as @variable_expense" do
      get :new, {}, valid_session
      assigns(:variable_expense).should be_a_new(VariableExpense)
    end
  end

  describe "GET edit" do
    it "assigns the requested variable_expense as @variable_expense" do
      variable_expense = VariableExpense.create! valid_attributes
      get :edit, {:id => variable_expense.to_param}, valid_session
      assigns(:variable_expense).should eq(variable_expense)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VariableExpense" do
        expect {
          post :create, {:variable_expense => valid_attributes}, valid_session
        }.to change(VariableExpense, :count).by(1)
      end

      it "assigns a newly created variable_expense as @variable_expense" do
        post :create, {:variable_expense => valid_attributes}, valid_session
        assigns(:variable_expense).should be_a(VariableExpense)
        assigns(:variable_expense).should be_persisted
      end

      it "redirects to the created variable_expense" do
        post :create, {:variable_expense => valid_attributes}, valid_session
        response.should redirect_to(VariableExpense.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved variable_expense as @variable_expense" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariableExpense.any_instance.stub(:save).and_return(false)
        post :create, {:variable_expense => {}}, valid_session
        assigns(:variable_expense).should be_a_new(VariableExpense)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VariableExpense.any_instance.stub(:save).and_return(false)
        post :create, {:variable_expense => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested variable_expense" do
        variable_expense = VariableExpense.create! valid_attributes
        # Assuming there are no other variable_expenses in the database, this
        # specifies that the VariableExpense created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VariableExpense.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => variable_expense.to_param, :variable_expense => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested variable_expense as @variable_expense" do
        variable_expense = VariableExpense.create! valid_attributes
        put :update, {:id => variable_expense.to_param, :variable_expense => valid_attributes}, valid_session
        assigns(:variable_expense).should eq(variable_expense)
      end

      it "redirects to the variable_expense" do
        variable_expense = VariableExpense.create! valid_attributes
        put :update, {:id => variable_expense.to_param, :variable_expense => valid_attributes}, valid_session
        response.should redirect_to(variable_expense)
      end
    end

    describe "with invalid params" do
      it "assigns the variable_expense as @variable_expense" do
        variable_expense = VariableExpense.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariableExpense.any_instance.stub(:save).and_return(false)
        put :update, {:id => variable_expense.to_param, :variable_expense => {}}, valid_session
        assigns(:variable_expense).should eq(variable_expense)
      end

      it "re-renders the 'edit' template" do
        variable_expense = VariableExpense.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VariableExpense.any_instance.stub(:save).and_return(false)
        put :update, {:id => variable_expense.to_param, :variable_expense => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested variable_expense" do
      variable_expense = VariableExpense.create! valid_attributes
      expect {
        delete :destroy, {:id => variable_expense.to_param}, valid_session
      }.to change(VariableExpense, :count).by(-1)
    end

    it "redirects to the variable_expenses list" do
      variable_expense = VariableExpense.create! valid_attributes
      delete :destroy, {:id => variable_expense.to_param}, valid_session
      response.should redirect_to(variable_expenses_url)
    end
  end

end
